---
driver:
  name: vagrant

provisioner:
  name: chef_zero-scheduled-task

platforms:
- name: centos-6.5
  driver_config:
    require_chef_omnibus: true
    box: opscode-centos-6.5
    box_url: http://filer.criteo.prod/boxes/opscode-centos-6.5.box
- name: windows-2012r2
  driver_config:
    require_chef_omnibus: false
    box: windows-2012r2-standard
    box_url: http://filer.criteo.prod:8080/boxes/windows-2008r2-web-core-dotnet45.box

suites:
- name: default
  run_list: [
    'recipe[ms_dotnet::ms_dotnet3]',
  ]
